[package]
name = "eagle_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3"
clap={version = "4.4.4", features = ["derive"]}
serde_json = { version = "1.0.106"}