server:
  port: 8115 #服务端口
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: mysql_connect # 服务名
  data:
    mongodb:
      uri: mongodb://user:123456@h131:27020/mydb
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://h131:3306/hsp_mybatis?useSSL=true&requireSSL=true&verifyServerCertificate=false&characterEncoding=UTF-8
    username: root
    password: 123456 # 需要配置环境变量MYSQL_PASSWORD

  servlet:
    multipart:
      maxFileSize: 10MB

  devtools:
    restart:
      enabled: true
logging:
  level:
    root: info
    yun:
      ling:
        pm:
          mapper: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #控制台 不打印sql
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl #打印sql到日志文件
